### ISSUE TITLE
Consider generating a website

### ISSUE THREAD

**Issue by madebr** [qchateau/conan-center-bot#23] opened 2020-11-19 16:17 UTC
The more functionality you/we add to conan-center-bot, the more the reports at at #1 and https://github.com/conan-io/conan-center-index/issues/3470 will get more complicated.

That's why I suggest to create a webpage.

I have good experience with [lektor](https://www.getlektor.com/).
This is a python static website generator. 
(I don't know much about css+html+javascript though)

If the backend creates a python object with all the information,
then the frontends can generate a website and issue markdown.
By using github pages, the site can be published at e.g. https://qchateau.github.io/conan-center-bot.

**Comment by qchateau** [comment] 2020-11-19 19:06
That can be the next step.

But instead of generating the website, I'd just write the website, which would load data from a JSON. Then CCB can simply re-generate and update the JSON file when it runs. We just need to refresh the data, not the whole website.

**Comment by madebr** [comment] 2020-11-19 19:17
Generating these (and more) artefacts will also make it easier for people to create extensions.
If loading would be non-trivial, it would be nice if ccbot would provide a loader/class of some sort.

**Comment by qchateau** [comment] 2020-11-19 19:21
> If loading would be non-trivial, it would be nice if ccbot would provide a loader/class of some sort.

What do you mean ? 

What I have in mind is just a JSON file deployed to github pages (which means available through HTTPS to anyone) which CCB will keep up-to-date

**Comment by madebr** [comment] 2020-11-19 19:47
JSON files can sometimes be quite complex containing cross references.
Also your ccbot library will probably contain util functions/classes to make working with repos easier. I was asking to consider serializing and deserializing the data.

**Comment by qchateau** [comment] 2020-11-20 18:59
Ok, there we go: https://qchateau.github.io/conan-center-bot

It's pretty much the same thing that we have in the issue atm, but as you said it's easier to add features.

The problem is that it has even less visibility than the issue in CCI

**Comment by madebr** [comment] 2020-11-20 19:15
Very nice!
Somebody in this thread had very little sleep :smile: 

I would let the CCI issue consist of a table with the basic data and link back to the issue.
Right now, the bot only checks for newer versions.
But it can check many more things, such as outdated dependencies, violations against the hooks, ...
The website is more welcoming to adding this information as the issue will feel overcrowded quickly.

**Comment by qchateau** [comment] 2020-11-20 20:03
Yeah I've got plenty of free time atm, but it's not gonna last :)

I guess I'll just link the website in the issue then

**Comment by qchateau** [comment] 2020-11-23 11:14
I'm closing this issue now that there is a website. We can always create more issues to add features to it

**Closed by qchateau** 2020-11-23 11:14 UTC
